// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogLineCount():Promise<number>;

export function LogLine():Promise<void>;

export function StartDpsTracker():Promise<void>;
