// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogLineCount() {
  return window['go']['main']['App']['GetLogLineCount']();
}

export function LogLine() {
  return window['go']['main']['App']['LogLine']();
}

export function StartDpsTracker() {
  return window['go']['main']['App']['StartDpsTracker']();
}
